version: "3"

services:
  backend:
    build: ./backend
    container_name: django_mssql_container
    image: django_mssql_image
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    # restart: always